services:
  bookmarks:
    image: jorgemartinezpizarro/bookmarks:latest
    restart: always
    ports:
      - ${PORT}:3000
    environment:
      - NEXTCLOUD_URL=${NEXTCLOUD_URL}
      - PORT=${PORT}
  