services:
  #bookmarks:
  #  image: jorgemartinezpizarro/bookmarks:latest
  #  restart: always
  #  ports:
  #    - ${PORT}:3000
  #  environment:
  #    - OPEN_AI_API_KEY=${OPEN_AI_API_KEY}
  #    - NEXT_PUBLIC_NEXTCLOUD_URL=${NEXT_PUBLIC_NEXTCLOUD_URL}
  #    - PORT=${PORT}
  wordlist:
    image: jorgemartinezpizarro/wordlist:latest
    ports:
      - 1009:8080
  stockfish:
    image: jorgemartinezpizarro/stockfish:latest
    ports:
      - 1007:8080
  gpt:
    image: jorgemartinezpizarro/gpt:latest
    ports:
      - 1008:5000